# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSVGIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('svg', models.FileField(help_text='Please check the SVG Icon source for malicious code before uploading it.', upload_to='svg_icons/', verbose_name='SVG Icon File')),
            ],
            options={
                'verbose_name': 'Custom SVG Icon',
                'verbose_name_plural': 'Custom SVG Icons',
                'ordering': ('name',),
            },
        ),
    ]
