# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAttributesAsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='meta_metaattributesasplugin', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'verbose_name': 'Meta Attributes as Plugin',
                'verbose_name_plural': 'Meta Attributes as Plugin',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterModelOptions(
            name='metaattributes',
            options={'verbose_name': 'Meta Attributes', 'verbose_name_plural': 'Meta Attributes'},
        ),
        migrations.AddField(
            model_name='metaattributes',
            name='plugins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.MetaAttributesAsPlugin'),
        ),
    ]
