# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 08:59
from __future__ import unicode_literals

from django.db import migrations
import rh.apps.icons.base


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20180315_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaattributes',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='metaattributes',
            name='plugins',
        ),
        migrations.AddField(
            model_name='metaattributes',
            name='svg_icon',
            field=rh.apps.icons.base.IconField(blank=True, max_length=100, null=True, verbose_name='SVG Icon'),
        ),
    ]
