# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 10:26
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('meta', '0003_auto_20180321_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaattributesasplugin',
            name='cmsplugin_ptr',
        ),
        migrations.AddField(
            model_name='metaattributes',
            name='lead',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Short description of the page. Used by the step list plugin.', max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='MetaAttributesAsPlugin',
        ),
    ]
