# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('meta', '0004_auto_20180322_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaattributes',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
