# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('meta', '0005_metaattributes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagination',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='meta_pagination', serialize=False, to='cms.CMSPlugin')),
                ('show_numbers', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
