language: python
python: 3.6
services:
  - postgresql
env:
  - DATABASE_URL=postgres://postgres@localhost:5432/rh
before_install:
  - pip install -U pipenv
install: pipenv install --deploy --dev
before_script:
  - psql -c 'create database rh;' -U postgres
script:
  - pytest --cov-report=term
