# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('steps', '0003_stepfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepfile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='steplink',
            name='id',
        ),
        migrations.AddField(
            model_name='stepfile',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='steps_stepfile', serialize=False, to='cms.CMSPlugin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steplink',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='steps_steplink', serialize=False, to='cms.CMSPlugin'),
            preserve_default=False,
        ),
    ]
