# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 23:48
from __future__ import unicode_literals

from django.db import migrations
import rh.apps.icons.base


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_auto_20180406_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='svg_icon',
            field=rh.apps.icons.base.IconField(blank=True, max_length=100, null=True, verbose_name='SVG Icon'),
        ),
    ]
