# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0005_step_svg_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepfile',
            name='link_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
