# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_block_style'),
        ('case_studies', '0002_auto_20180321_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='use_cases',
            field=models.ManyToManyField(to='content.IconCard'),
        ),
    ]
