# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0003_casestudy_use_cases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tagulous_CaseStudy_tags',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='tags',
        ),
    ]
