# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0004_auto_20180404_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='country',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='region',
            field=models.CharField(choices=[('americas', 'The Americas and Caribbean'), ('europe-asia-c', 'Europe and Central Asia'), ('pacific-asia-e', 'East Asia and the Pacific'), ('africa-e-s', 'Eastern and Southern Africa'), ('middle-east-africa', 'Middle East and North Africa'), ('asia-s', 'South Asia'), ('africa-w-c', 'West and Central Africa')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
