# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0005_auto_20180405_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='use_cases',
            field=models.ManyToManyField(to='cms.Page'),
        ),
    ]
