# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0006_auto_20180409_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
