# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 01:32
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('case_studies', '0007_casestudy_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='lead_content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_case_study', slotname='case_study_lead_content', to='cms.Placeholder', verbose_name='Case Study Lead Content'),
        ),
    ]
