# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 12:02
from __future__ import unicode_literals

from django.db import migrations
import rh.apps.icons.base


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_cardgrid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconcard',
            name='icon',
        ),
        migrations.AddField(
            model_name='iconcard',
            name='svg_icon',
            field=rh.apps.icons.base.IconField(blank=True, max_length=100, null=True, verbose_name='SVG Icon'),
        ),
    ]
