# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_imagecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='link_style',
            field=models.CharField(choices=[('button', 'Button'), ('link', 'Link')], default='button', max_length=10),
        ),
    ]
