# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 08:56
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20180321_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgrid',
            name='root',
            field=cms.models.fields.PageField(blank=True, help_text='Select a root page to list all of its children as cards. If this is left empty, you will have to manually add cards to the grid.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
    ]
