# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20180321_0856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageCard',
            new_name='PhotoCard',
        ),
    ]
