# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20180322_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='style',
            field=models.CharField(choices=[('default', 'White'), ('light', 'Light'), ('dark', 'Dark')], default='default', max_length=32),
        ),
    ]
