# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 04:11
from __future__ import unicode_literals

from django.db import migrations


def merge(apps, schema_editor):
    CMSPlugin = apps.get_model('cms.CMSPlugin')
    CMSPlugin.objects.filter(plugin_type='SectionCardsPlugin').update(
        plugin_type='SectionPlugin')


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_block_style'),
    ]

    operations = [
        migrations.RunPython(merge, reverse_code=migrations.RunPython.noop)
    ]
