# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('content', '0012_merge_sectioncardsplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawHTML',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_rawhtml', serialize=False, to='cms.CMSPlugin')),
                ('html', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
