# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 22:50
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_link.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('content', '0014_blockquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconcard',
            name='fix_external_link',
            field=models.URLField(blank=True, help_text='Provide a valid URL to an external website.', max_length=2040, validators=[djangocms_link.validators.IntranetURLValidator(intranet_host_re=None)], verbose_name='External link'),
        ),
        migrations.AddField(
            model_name='iconcard',
            name='fix_internal_link',
            field=cms.models.fields.PageField(blank=True, help_text='If provided, overrides the external link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Internal link'),
        ),
        migrations.AddField(
            model_name='iconcard',
            name='fix_link_style',
            field=models.CharField(choices=[('button', 'Button'), ('link', 'Link')], default='button', max_length=10),
        ),
        migrations.AddField(
            model_name='iconcard',
            name='fix_link_text',
            field=models.CharField(blank=True, max_length=64, verbose_name='Link Text'),
        ),
        migrations.AddField(
            model_name='iconcard',
            name='fix_title',
            field=models.CharField(default='', max_length=256, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iconcard',
            name='fix_body',
            field=models.TextField(default='', verbose_name='body'),
            preserve_default=False
        ),
        migrations.AddField(
            model_name='iconcard',
            name='fix_cmsplugin_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='+', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AddField(
            model_name='photocard',
            name='fix_external_link',
            field=models.URLField(blank=True, help_text='Provide a valid URL to an external website.', max_length=2040, validators=[djangocms_link.validators.IntranetURLValidator(intranet_host_re=None)], verbose_name='External link'),
        ),
        migrations.AddField(
            model_name='photocard',
            name='fix_internal_link',
            field=cms.models.fields.PageField(blank=True, help_text='If provided, overrides the external link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Internal link'),
        ),
        migrations.AddField(
            model_name='photocard',
            name='fix_link_style',
            field=models.CharField(choices=[('button', 'Button'), ('link', 'Link')], default='button', max_length=10),
        ),
        migrations.AddField(
            model_name='photocard',
            name='fix_link_text',
            field=models.CharField(blank=True, max_length=64, verbose_name='Link Text'),
        ),
        migrations.AddField(
            model_name='photocard',
            name='fix_title',
            field=models.CharField(default='', max_length=256, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photocard',
            name='fix_body',
            field=models.TextField(default='', verbose_name='body'),
            preserve_default=False
        ),
        migrations.AddField(
            model_name='photocard',
            name='fix_cmsplugin_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='+', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
