# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations.operations.models import ModelOperation


class ChangeModelBases(ModelOperation):

    def __init__(self, name, bases):
        self.bases = bases
        super().__init__(name)

    def state_forwards(self, app_label, state):
        model_state = state.models[app_label, self.name_lower]
        model_state.bases = list(self.bases)
        state.reload_model(app_label, self.name_lower, delay=True)

    def database_forwards(self, *args, **kwargs):
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('content', '0016_fix_cards'),
    ]

    operations = [
        ChangeModelBases('IconCard', bases=('cms.cmsplugin', models.Model)),
        ChangeModelBases('PhotoCard', bases=('cms.cmsplugin', models.Model)),
        migrations.RenameField(
            model_name='iconcard',
            old_name='fix_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='iconcard',
            old_name='fix_external_link',
            new_name='external_link',
        ),
        migrations.RenameField(
            model_name='iconcard',
            old_name='fix_internal_link',
            new_name='internal_link',
        ),
        migrations.RenameField(
            model_name='iconcard',
            old_name='fix_link_style',
            new_name='link_style',
        ),
        migrations.RenameField(
            model_name='iconcard',
            old_name='fix_link_text',
            new_name='link_text',
        ),
        migrations.RenameField(
            model_name='iconcard',
            old_name='fix_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='photocard',
            old_name='fix_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='photocard',
            old_name='fix_external_link',
            new_name='external_link',
        ),
        migrations.RenameField(
            model_name='photocard',
            old_name='fix_internal_link',
            new_name='internal_link',
        ),
        migrations.RenameField(
            model_name='photocard',
            old_name='fix_link_style',
            new_name='link_style',
        ),
        migrations.RenameField(
            model_name='photocard',
            old_name='fix_link_text',
            new_name='link_text',
        ),
        migrations.RenameField(
            model_name='photocard',
            old_name='fix_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='iconcard',
            name='block_ptr',
        ),
        migrations.RemoveField(
            model_name='photocard',
            name='block_ptr',
        ),
        migrations.RenameField(
            model_name='iconcard',
            old_name='fix_cmsplugin_ptr',
            new_name='cmsplugin_ptr',
        ),
        migrations.RenameField(
            model_name='photocard',
            old_name='fix_cmsplugin_ptr',
            new_name='cmsplugin_ptr',
        ),
        migrations.AlterField(
            model_name='iconcard',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_iconcard', serialize=False, to='cms.CMSPlugin'),

        ),
        migrations.AlterField(
            model_name='photocard',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='content_photocard', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
