# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 22:51
from __future__ import unicode_literals

from django.db import migrations


def remove_orphaned_sections(apps, schema_editor):
    Section = apps.get_model('content.Section')
    IconCard = apps.get_model('content.IconCard')
    PhotoCard = apps.get_model('content.PhotoCard')
    for section in Section.objects.filter(pk__in=IconCard.objects.values_list('pk')):
        section.delete(keep_parents=True)
    for section in Section.objects.filter(pk__in=PhotoCard.objects.values_list('pk')):
        section.delete(keep_parents=True)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_rename_block_to_section'),
    ]

    operations = [
        migrations.RunPython(
            remove_orphaned_sections, reverse_code=migrations.RunPython.noop),
    ]
