# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgrid',
            name='style',
            field=models.CharField(choices=[('default', 'White'), ('light', 'Light'), ('dark', 'Dark')], default='default', max_length=32),
        ),
    ]
