# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_cardgrid_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconcard',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
