# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_populate_iconcard_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconcard',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
