# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 03:41
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_link.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('content', '0024_auto_20180408_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='external_link',
            field=models.URLField(blank=True, help_text='Provide a valid URL to an external website.', max_length=2040, validators=[djangocms_link.validators.IntranetURLValidator(intranet_host_re=None)], verbose_name='External link'),
        ),
        migrations.AddField(
            model_name='hero',
            name='internal_link',
            field=cms.models.fields.PageField(blank=True, help_text='If provided, overrides the external link.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='Internal link'),
        ),
        migrations.AddField(
            model_name='hero',
            name='link_style',
            field=models.CharField(choices=[('button', 'Button'), ('link', 'Link')], default='button', max_length=10),
        ),
        migrations.AddField(
            model_name='hero',
            name='link_text',
            field=models.CharField(blank=True, max_length=64, verbose_name='Link Text'),
        ),
    ]
