# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 17:35
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20180418_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgrid',
            name='style',
            field=models.CharField(choices=[('default', 'White'), ('minimal', 'Minimal'), ('light', 'Light'), ('dark', 'Dark')], default='default', max_length=32),
        ),
        migrations.AlterField(
            model_name='hero',
            name='internal_link',
            field=cms.models.fields.PageField(blank=True, help_text='If provided, overrides the external link.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Internal link'),
        ),
        migrations.AlterField(
            model_name='section',
            name='style',
            field=models.CharField(choices=[('default', 'White'), ('minimal', 'Minimal'), ('light', 'Light'), ('dark', 'Dark')], default='default', max_length=32),
        ),
    ]
